image: mischief/docker-golang
env:
  - GOPATH=/var/cache/drone
script:
  - 'sleep 30'
  - 'true'
notify:
  email:
    on_success: true
    on_failure: true
    urls:
      - http://drone.prismaticgreen.com:4000
  irc:
    nick: testgobot
    server: chat.freenode.net
    channel: '#jordanetest'
    on_started: true
    on_success: true
    on_failure: true
    ssl: true
